%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"
# Camera calibration and distortion parameters (OpenCV) 

Camera.fx: 1037.536376953125 
Camera.fy: 1038.532958984375
Camera.cx: 600.182861328125
Camera.cy: 358.40493774414062500

Camera.k1: 0.03784750
Camera.k2: -0.051872
Camera.p1: -0.000938
Camera.p2: 0.000157



# Camera resolution
Camera.width: 1280
Camera.height: 720

# Camera frames per second 
Camera.fps: 20.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Transformation from body-frame (imu) to camera
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [0.99996652, 0.00430873, 0.00695718, -0.04777362,
          0.00434878 , -0.99997401, -0.00575128, -0.00223731,
          0.00693222, 0.00578135, -0.99995926, -0.02160071,
          0.0, 0.0, 0.0, 1.0]
# Tbc: !!opencv-matrix  # from vins mono calibration file
#   rows: 4
#   cols: 4
#   dt: f
#   data: [-0.9995250378696743, 0.0075842033363785165, -0.030214670573904204, 0.044511917113940799, 
#          0.029940114644659861, -0.034023430206013172, -0.99897246995704592, -0.073197096234105752,
#         -0.0086044170750674241, -0.99939225835343004, 0.033779845322755464, -0.047972907300764499,
#          0.0, 0.0, 0.0, 1.0]


# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 0.00017 # rad/s^0.5 
IMU.NoiseAcc: 0.002 # m/s^1.5
IMU.GyroWalk: 0.00002 # rad/s^1.5
IMU.AccWalk: 0.005 # m/s^2.5
IMU.Frequency: 200


#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1500 # Tested with 1250

# ORB Extractor: Scale factor between levels in the scale pyramid   
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid  
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast     
# ORBextractor.iniThFAST: 20
# ORBextractor.minThFAST: 7
ORBextractor.iniThFAST: 20 # 20
ORBextractor.minThFAST: 7 # 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5 # -1.8
Viewer.ViewpointF: 500
